### ISSUE TITLE
Can't drag app

### ISSUE THREAD

**Issue by jorgemoya** [mortenjust/PocketCastsOSX#10]
For some reason, I'm unable to reposition the app with my mouse. I can move it around using Spectacles, though. I can resize the window, minimize, etc.

I'm on El Capitan.

**Comment by mortenjust** [comment]
Are you 1.2.2?
https://github.com/mortenjust/PocketCastsOSX/releases/tag/1.2.2

**Comment by jorgemoya** [comment]
Sorry I guess I was using a previous version (clean installed this weekend). Now works as expected.
