### ISSUE TITLE
Clicking links does not open them

### ISSUE THREAD

**Issue by trevormkay** [mortenjust/PocketCastsOSX#11]
When you click a link, it should open in Safari. Currently links do nothing.

**Comment by mortenjust** [comment]
Good catch. I take it this is shownotes? If so, which podcast is an example?

**Comment by trevormkay** [comment]
Yep, in the show notes. ATP is a good podcast to try, that has lots of links in the show notes.

**Comment by mortenjust** [comment]
Fixed in 1.25. Thanks for the bug report! https://github.com/mortenjust/PocketCastsOSX/releases/
