### ISSUE TITLE
Close button quits the app

### ISSUE THREAD

**Issue by sanderploegsma** [mortenjust/PocketCastsOSX#15]
Great app! I noticed that the app quits when closing the window, instead of hiding. Would be nice if it remains running without an open window, like other native OS X apps.

**Comment by samhh** [comment]
I agree with this. It also happens if you hit CMD+W, which should only hide the window. It should only quit fully when you hit CMD+Q.

**Comment by sakuranbokun** [comment]
Personally I prefer how it works now, but then again, I wish all OS X apps would quit when the close icon is clicked.

**Comment by samhh** [comment]
Sure @sakuranbokun, but consistency with the OS and the current ecosystem of apps is more important in my opinion, at least as the default. I'm sure an option could be made for this?

**Comment by sanderploegsma** [comment]
I already posted this in #17 but I'll repeat it here for those who missed it: if anyone needs a version without this issue, [get it here](https://github.com/sanderploegsma/PocketCastsOSX/releases/tag/1.2.3).

**Comment by mortenjust** [comment]
I think this is working as intended. It seems to be the direction Apple wants to take macOS. 

About a year ago, I had an app rejected from the Mac store because it didn't quit the app when the user clicked close. The red button, they said, should not quit the app if the app is document-based. 

In El Capitan, these non-document-based apps do in fact quit when pressing the red button: Mac Notes, Reminders, App Store, Preferences. Other apps like iTunes and iBooks don't which is a bit confusing.

**Comment by sanderploegsma** [comment]
Yes, but those apps don't have any background processes, which might be why they don't have to remain active when the window closes. iTunes and other music apps all have the same behaviour: close instead of quit, to make sure they keep playing in the background. 

I prefer hiding windows I don't have to interact with to keep my workspace a bit cleaner, that's why I opened the issue.

**Comment by mortenjust** [comment]
That's a fair point, although the app I got rejected for close-hiding had a background process. To me it feels a bit confusing that they have different behavior. Just out of curiosity, when do you use hide and when do you use minimize? I mean you, as a macOS user.

**Comment by sanderploegsma** [comment]
Personally I never minimize apps, I hate having all those minimized windows in the dock, as the dock already contains the app itself. Unnecessary clutter, if you will. So I always use the close button.

**Comment by jamesduffy** [comment]
Jumping in here. I use this app as well as [Radiant Player](http://radiant-player.github.io/radiant-player-mac/). I wanted a desktop app for Pocket Casts so I can close the window. As it is now there isn't much benefit over keeping it open in a tab.

**Comment by sanderploegsma** [comment]
Ok since the preference on this behaviour seems to be divided, would it be an idea to create a setting in the app?
