### ISSUE TITLE
Cmd+key shortcuts doesn't work

### ISSUE THREAD

**Issue by z0rc** [mortenjust/PocketCastsOSX#20]
Pressing Cmd+V or Cmd+C in text fields (search, login form) doesn't do expected action, text isn't pasted nor copied. Also pressing mentioned shortcut generate the alert sound, like there was some error. Copying and pasting via context menu works fine.

**Comment by matthewmorek** [comment]
I do not seem to have this issue on macOS Sierra 10.12. Copying and pasting passwords seem to work just fine for me.

**Comment by mortenjust** [comment]
Also works here. Feel free to reopen with repro steps
