### ISSUE TITLE
Graphic glitch

### ISSUE THREAD

**Issue by teemue** [mortenjust/PocketCastsOSX#21]
Main window has glitch on the top corners. OS: macOS Sierra 10.12.

[http://s16.postimg.org/x441zsmlh/Na_ytto_kuva_2016_09_25_kello_23_55_37.png](url)

**Comment by ymar** [comment]
I have the exact same issue after updating to Sierra
http://d.pr/i/Lefc

**Comment by bpenda** [comment]
I just submitted a pull request with a fix, it was a one liner

**Comment by ymar** [comment]
Thanks a lot!

**Comment by Kraahkan** [comment]
Also having this D=

**Comment by cggaurav** [comment]
The images are 404 ^ . Maybe its this? ![](http://d.cggaurav.net/wvmR/2DkfxsT9+)

**Comment by mortenjust** [comment]
fixed in latest release - thanks!
