### ISSUE TITLE
Run in background / no window present

### ISSUE THREAD

**Issue by apfelchips** [mortenjust/PocketCastsOSX#29]
The usual behavior of most OS X apps is to keep running even when all windows have been closed, this is especially true for media playback applications.

So please let PocketCastsOSX respond to cmd+w as if it were a cmd+h shortcut and just hide the window, but keep the content playing in the background.

Thanks.

**Comment by sanderploegsma** [comment]
I already mentioned this in #15 and actually proposed a fix in #17, but unfortunately the author doesn't seem to agree with this notion.

**Comment by mortenjust** [comment]
Happy to reconsider since this is a common request. One question I have though, about #17 is, if I close the window, and let the sound continue, how do I get the UI back?

**Comment by sanderploegsma** [comment]
You just click the dock icon :) it should be exactly the same as iTunes, Spotify and other desktop music players. If not, let me know!

**Comment by mortenjust** [comment]
For some weird reason that doesn't seem to work on your branch (I click the icon, nothing happens) - but it does work this way in the new version I just released, although it doesn't contain your PR - sorry!

**Comment by sanderploegsma** [comment]
You sure? I've been running that exact build for months (and some others have as well) and never had issues with it.

**Comment by sanderploegsma** [comment]
Anyway, I just downloaded the new release and it seems to have the same functionality, so I'll close my PR.
