### ISSUE TITLE
Leaving app in background

### ISSUE THREAD

**Issue by matthewdias** [mortenjust/PocketCastsOSX#3]
After closing the window but leaving the app running, you can't open the window again by clicking the dock icon. The app needs to be restarted.

**Comment by mortenjust** [comment]
I'm not able to reproduce this bug. Which MacOS version are you on?

**Comment by matthewdias** [comment]
bug still exists. I'm on 10.10.5. sorry for the late response

**Comment by mortenjust** [comment]
Fixed in 1.2 https://github.com/mortenjust/PocketCastsOSX/releases/tag/1.2

**Comment by matthewdias** [comment]
I think the release was not built properly. On launch it says it can't be opened and prompts me to move to trash.

**Comment by matthewdias** [comment]
I think your certificate may have been revoked. For now I'll just build manually. 
     $ sudo spctl --assess --verbose=4 /Applications/PocketCasts.app
     output: /Applications/PocketCasts.app: CSSMERR_TP_CERT_REVOKED

**Comment by mortenjust** [comment]
I was unable to build a signed build after getting a new mac. Revoked all
my certificates in the member area, but still get the error while building
in xcode. Would appreciate any help

**Comment by matthewdias** [comment]
what error are you getting in xcode?

**Comment by mortenjust** [comment]
<img width="603" alt="screenshot10 22 pm" src="https://cloud.githubusercontent.com/assets/1548468/10213421/c349ca9a-67c1-11e5-8f2a-487f5f285a26.png">

I don't have access to my old mac. So I tried revoking all certificates I could find. Removed my Apple account in xcode, put it back in, and still got this.

**Comment by matthewdias** [comment]
Hm you maybe need to contact apple developer support for this one. Seems like a problem on their end.
