### ISSUE TITLE
Resize App Icon size to match other apps

### ISSUE THREAD

**Issue by goodwinchris** [mortenjust/PocketCastsOSX#30]
The PocketCast App Icon is larger than spotify, sparrow, chrome, firefox. Can we resize so it looks a bit better in the dock?

I'm also noticing the color is slightly off as opposed to the top bar of the application.

**Comment by mortenjust** [comment]
Hey Chris - did you grab the latest version from a few weeks back? 

![image](https://cloud.githubusercontent.com/assets/1548468/22451001/95db6c4c-e71f-11e6-91c5-924df104ccc2.png)

**Comment by goodwinchris** [comment]
@mortenjust I thought I had but apparently hadn't. Thanks!
