### ISSUE TITLE
Unable to move the window

### ISSUE THREAD

**Issue by francisprovost** [mortenjust/PocketCastsOSX#4]
Hi,

I don't know if it's beacause I'm on the 10.11 beta but there's no "tool bar" or whatever the name is and I can't move the window around.

**Comment by mortenjust** [comment]
Aha, haven't tested on 1.11, but you should be able to move around using the invisible topbar, like this

![ovearound](https://cloud.githubusercontent.com/assets/1548468/9475067/2b016758-4b19-11e5-8b35-b10146963555.gif)

**Comment by francisprovost** [comment]
Just tried it again with the latest version and it highlight the "page" instead

**Comment by mortenjust** [comment]
Yikes. We'll have to wait and see if it's a beta bug or when I can upgrade my Mac or someone makes a pull request, whichever comes first. Marking as help wanted

**Comment by francisprovost** [comment]
Thanks for the answer and great job on the app btw. I'll take a look if I have some spear time (never worked on an osx app tho)

**Comment by mortenjust** [comment]
Should be fixed in the latest release. Thanks for reporting
