### ISSUE TITLE
Distortion when adjusting playback speed.

### ISSUE THREAD

**Issue by matthewdias** [mortenjust/PocketCastsOSX#5]

**Comment by joezorry** [comment]
Noticing this too.
However this issue is the same in the Safari browser.
Which makes sense since (without looking at the code), this uses the web-view which is the same as safari.

Wonder if this could be done via chromium/chrome view instead, where the sound works correctly.

**Comment by mortenjust** [comment]
Seems to be possible, but not without a bit of work http://stackoverflow.com/questions/31741433/could-anybody-explain-me-how-to-include-chromium-in-an-existing-xcode-project

**Comment by mortenjust** [comment]
Maybe it would be easier to file this bug with the PocketCast guys :smiley:

**Comment by joezorry** [comment]
@mortenjust that's probably the best solution, since all Safari users also is affected. I'll try to send them a tweet, they are usually good at responding.

**Comment by matthewdias** [comment]
https://twitter.com/shiftyjelly/status/704822309425704960
