### ISSUE TITLE
unable to start application

### ISSUE THREAD

**Issue by Domoel** [mortenjust/PocketCastsOSX#6]
Hey!

After updating to the release version of el capitan (coming from latest yosemite), i am unable to install the latest version of the wrapper. Im always getting the message that i am unable to open the object. infact i already disable the security app guard for the "Mac Appstore apps" to "no limitations".

**Comment by mortenjust** [comment]
It's a known issue. Got a new Mac and can't create a signed build because I
don't have the old developer profile. Not sure how to proceed

**Comment by drewcovi** [comment]
you'll need to export the profile from your old mac.... its a huge pain.

**Comment by mortenjust** [comment]
The old mac has been wiped. Any ideas?

**Comment by mortenjust** [comment]
Ha, wait, stopped it last minute from being wiped. Will recall the last release and compile again in a week.

**Comment by mortenjust** [comment]
This one should work. https://github.com/mortenjust/PocketCastsOSX/releases/tag/1.2.1
