### ISSUE TITLE
Unable to play podcasts since 1.2.1

### ISSUE THREAD

**Issue by z0rc** [mortenjust/PocketCastsOSX#7]
Application fails to load covers and play podcasts since upgrading to 1.2.1.
![screen shot 2015-10-16 at 12 25 57](https://cloud.githubusercontent.com/assets/787519/10538456/3a63a86c-7401-11e5-9ee4-a349528e8f97.png)

**Comment by z0rc** [comment]
Since web version works just fine, I assume there are some issues loading content from app via regular HTTP rather then HTTPS.

**Comment by luryus** [comment]
This is caused by El Capitan's new App Transport Security, which prevents HTTP connections. Probably the simplest (and maybe only possible) fix is to disable ATS.

**Comment by mortenjust** [comment]
Can you try with 10.11.1? Works fine for me without ATS changes.

**Comment by mortenjust** [comment]
Ah, for that particular podcast it doesn't work, got it. Now merging @luryus 's changes. Thanks guys!

**Comment by mortenjust** [comment]
Also added this fix as a release
